### ISSUE TITLE
Maps Module needs better error reporting

### ISSUE THREAD

**Issue by snixtho** [EvoEsports/EvoSC-sharp#170] opened 2023-07-17 09:04 UTC
Currently, the only message that occurs when adding a map fails is that "something went wrong". It doesn't give proper feedback to to the user of what went wrong, for example when a map already exists in the database.

**Comment by AtomicLiquid** [comment] 2023-07-23 12:50
Duplicate of #79

**Closed** 2023-07-23 12:50 UTC
Labels: bug, good first issue, module
